import { Order } from "./types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_001",
    orderNumber: "CV-2024-001",
    status: "DELIVERED",
    createdAt: "2024-11-15T10:30:00Z",
    updatedAt: "2024-11-20T14:00:00Z",
    total: 285000,
    trackingCode: "TCC123456789",
    shippingAddress: {
      fullName: "Juan Pérez",
      address: "Calle 85 # 15-23 Apto 401",
      city: "Bogotá",
      department: "Cundinamarca",
    },
    items: [
      {
        id: "item_001",
        productName: "Camiseta Lino Premium Verde",
        productImage: "/images/products/camiseta-lino-verde.jpg",
        color: "Verde Bosque",
        size: "M",
        quantity: 2,
        unitPrice: 85000,
      },
      {
        id: "item_002",
        productName: "Pantalón Algodón Orgánico",
        productImage: "/images/products/pantalon-algodon.jpg",
        color: "Beige Natural",
        size: "32",
        quantity: 1,
        unitPrice: 115000,
      },
    ],
  },
  {
    id: "ord_002",
    orderNumber: "CV-2025-008",
    status: "SHIPPED",
    createdAt: "2025-01-28T09:00:00Z",
    updatedAt: "2025-02-01T16:45:00Z",
    total: 145000,
    trackingCode: "TCC987654321",
    shippingAddress: {
      fullName: "Juan Pérez",
      address: "Calle 85 # 15-23 Apto 401",
      city: "Bogotá",
      department: "Cundinamarca",
    },
    items: [
      {
        id: "item_003",
        productName: "Blusa Seda Sostenible",
        productImage: "/images/products/blusa-seda.jpg",
        color: "Blanco Perla",
        size: "S",
        quantity: 1,
        unitPrice: 145000,
      },
    ],
  },
  {
    id: "ord_003",
    orderNumber: "CV-2025-015",
    status: "PROCESSING",
    createdAt: "2025-02-10T14:20:00Z",
    updatedAt: "2025-02-10T14:20:00Z",
    total: 320000,
    shippingAddress: {
      fullName: "Juan Pérez",
      address: "Calle 85 # 15-23 Apto 401",
      city: "Bogotá",
      department: "Cundinamarca",
    },
    items: [
      {
        id: "item_004",
        productName: "Chaqueta Reciclada Eco",
        productImage: "/images/products/chaqueta-eco.jpg",
        color: "Oliva",
        size: "L",
        quantity: 1,
        unitPrice: 220000,
      },
      {
        id: "item_005",
        productName: "Camiseta Lino Premium Crema",
        productImage: "/images/products/camiseta-lino-crema.jpg",
        color: "Crema",
        size: "M",
        quantity: 1,
        unitPrice: 100000,
      },
    ],
  },
  {
    id: "ord_004",
    orderNumber: "CV-2025-021",
    status: "PENDING",
    createdAt: "2025-02-18T11:05:00Z",
    updatedAt: "2025-02-18T11:05:00Z",
    total: 98000,
    shippingAddress: {
      fullName: "Juan Pérez",
      address: "Calle 85 # 15-23 Apto 401",
      city: "Bogotá",
      department: "Cundinamarca",
    },
    items: [
      {
        id: "item_006",
        productName: "Bufanda Lana Merino",
        productImage: "/images/products/bufanda-merino.jpg",
        color: "Terracota",
        size: "ONESIZE",
        quantity: 1,
        unitPrice: 98000,
      },
    ],
  },
  {
    id: "ord_005",
    orderNumber: "CV-2024-045",
    status: "CANCELLED",
    createdAt: "2024-09-05T08:15:00Z",
    updatedAt: "2024-09-07T10:30:00Z",
    total: 175000,
    shippingAddress: {
      fullName: "Juan Pérez",
      address: "Calle 85 # 15-23 Apto 401",
      city: "Bogotá",
      department: "Cundinamarca",
    },
    items: [
      {
        id: "item_007",
        productName: "Vestido Bambú Natural",
        productImage: "/images/products/vestido-bambu.jpg",
        color: "Marfil",
        size: "XS",
        quantity: 1,
        unitPrice: 175000,
      },
    ],
  },
];
